function [fitresult, gof] = fitData2Acorr(X, Y, ft, constrLow, constrHigh, paramData )
%fitData2Acorr(X,Y)
%  Create a fit.
%
%  Data for 'fitData2Acorr' fit:
%      X xAxis : X
%      Y Sample: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Apr-2015 16:25:00


%% Fit: 'fitAcorr'.
[xData, yData] = prepareCurveData( X, normax( Y ) );

% Set up fittype and options.
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Normalize = 'On';
opts.Algorithm = 'Trust-region';
opts.Display = 'final';
opts.Robust = 'LAR';
opts.StartPoint = [1 1 0.7]; % [N f sig]
opts.Lower = constrLow;
opts.Upper = constrHigh;
opts.MaxFunEvals = 5e3;
opts.MaxIter = 5e3;
opts.DiffMinChange = 1e-3;
opts.TolFun = 1e-9;
% opts.Upper = [Inf 50 20];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
figure( 'Name', 'fitAcorr' );
h = plot( fitresult, xData, yData );
hold on; plot(xData, yData);hold off;
legend( h, 'Y vs. X', 'fitAcorr', 'Location', 'NorthEast' );
% Label axes
xlabel( 'X' );
ylabel( 'Y' );
grid off


